baseURL: https://sharonxu-portfolio.netlify.app/
languageCode: en-us
title: Sharon Wenyu Xu's Portfolio Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
       Here I introduce several projects I did before, mostly in R and Python, and you can find my work below.
    title: Hi, my name is Sharon Xu! Welcome to my personal site.
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Park Rd
        title: London Business School, Regent's Park
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: sxu.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 7421898849
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: LBS AM01
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #- icon: fa-twitter
        #label: Twitter
        #url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/profile.php?id=100027590620453
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/sharonx112/
      - icon: fa-github
        label: GitHub
        url: https://github.com/SharonXuuu
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/sharon-wenyu-xu
  image: ''
  name: Your name
  navigation:
    #button1:
      #- name: Get Started
       # url: blogs
    #button2:
      #- name: Log In
        #url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      #- name: Generic Blog
        #url: blogs/ipsum
      #- name: Elements
        #url: elements.html
    menu: Menu
    title: Sharon Xu
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpeg
        subtitle: WHO I AM
        title: About Sharon
        url: blogs/about_sharon
      - image: pic02.jpg
        subtitle: Python
        title: Machine Learning Project
        url: blogs/ml
      - image: pic03.jpg
        subtitle: Python
        title: NYU Business and Economics Honors Program
        url: blogs/honors
      - image: pic04.jpg
        subtitle: R
        title: Youth Risk Behavior Surveillance
        url: blogs/youth
      - image: pic05.jpg
        subtitle: R
        title: 2016 California Contributors plots
        url: blogs/ca
      - image: pic06.jpg
        subtitle: R
        title: Omega Group plc- Pay Discrimination
        url: blogs/omega
  two:
    buttonText: Get Started
    enable: yes
    subtitle: Here is a quick overview about my projects. More blogs are coming soon...
    title: Project Gallery
    url: blogs
